name: 41willcome
favicon: null
layout_spectrum: 0.2575
typography_spectrum: 0.75049
title: 41 Will Come
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#cdcdcd'
    - '#979797'
    - '#3e3e3e'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
