name: 41willcome
favicon: null
layout_spectrum: 0.322777813533321
typography_spectrum: 0.651748145930469
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#f7eb00'
    - '#fbfbfb'
    - '#575300'
    - '#ada618'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
