name: 41willcome
favicon: null
layout_spectrum: 0.5119
typography_spectrum: 0.75049
title: 41 Will Come
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#f7eb00'
    - '#fbfbfb'
    - '#575300'
    - '#ada618'
  brandStrength: 0
  lightness: 1
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
